### ISSUE TITLE
ModuleNotFoundError: No module named 'dataclasses'

### ISSUE THREAD

**Issue by med** [tmilovanov/wisecreator#27]
I got this problem on win10 python3

D:\Dicts\programs\wisecreator-1.0>wisecreator ./test_books/wild.mobi
Traceback (most recent call last):
  File "C:\Python\Python36\Scripts\wisecreator-script.py", line 11, in <module>
    load_entry_point('wisecreator==1.0.0', 'console_scripts', 'wisecreator')()
  File "C:\Python\Python36\lib\site-packages\pkg_resources\__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Python\Python36\lib\site-packages\pkg_resources\__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "C:\Python\Python36\lib\site-packages\pkg_resources\__init__.py", line 2346, in load
    return self.resolve()
  File "C:\Python\Python36\lib\site-packages\pkg_resources\__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "C:\Python\Python36\lib\site-packages\wisecreator\main.py", line 15, in <module>
    from dataclasses import dataclass
ModuleNotFoundError: No module named 'dataclasses'

I fixed it after execute "pip install dataclasses"
Hope it could be fixed and others do not need to do this

**Comment by tmilovanov** [comment]
Thank you!
Fixed
