### ISSUE TITLE
Missing folder third_party/KindleUnpack/lib

### ISSUE THREAD

**Issue by du-song** [tmilovanov/wisecreator#42]
probably bc .git_ignore is too broad.

**Comment by thanhmd** [comment]
Just replace all the files within by the files in this repo: https://github.com/kevinhendricks/KindleUnpack

**Comment by Alexander-Serov** [comment]
Same issue. `KindleUnpack` is present but not found on script launch.
```
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Caskroom/miniconda/base/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/user/git/wisecreator/wisecreator/main.py", line 14, in <module>
    from wisecreator import book as ww_book
  File "/Users/user/git/wisecreator/wisecreator/book.py", line 12, in <module>
    from wisecreator.third_party.KindleUnpack.lib.kindleunpack import unpackBook
ModuleNotFoundError: No module named 'wisecreator.third_party.KindleUnpack.lib'
```

**Comment by trungquandev** [comment]
> Just replace all the files within by the files in this repo: https://github.com/kevinhendricks/KindleUnpack

@thanhmd Cảm ơn người anh em nhé =))

**Comment by ALevkas** [comment]
> Just replace all the files within by the files in this repo: https://github.com/kevinhendricks/KindleUnpack

It is still functioning. Thx!
