### ISSUE TITLE
KindleUnpack lib error

### ISSUE THREAD

**Issue by gallexy** [tmilovanov/wisecreator#47]
version 1.1 worked well, but when I try the latest version(2.0),
It reported cannot find lib.unpackBook 

testbooks liu$ wisecreator orson.mobi
Traceback (most recent call last):
  File "/Users/liu/pyproject/wisecreator2/env/bin/wisecreator", line 5, in <module>
    from wisecreator.main import main
  File "/Users/liu/pyproject/wisecreator2/env/lib/python3.9/site-packages/wisecreator/main.py", line 14, in <module>
    from wisecreator import book as ww_book
  File "/Users/liu/pyproject/wisecreator2/env/lib/python3.9/site-packages/wisecreator/book.py", line 12, in <module>
    from wisecreator.third_party.KindleUnpack.lib.kindleunpack import unpackBook
ModuleNotFoundError: No module named 'wisecreator.third_party.KindleUnpack'

**Comment by gallexy** [comment]
I checked the source code of KindleUnpack, but can not find any directory named lib, only libgui there.

**Comment by gallexy** [comment]
I found it from original KindleUnpack repository:
https://github.com/kevinhendricks/KindleUnpack.
It works well.
